import React, { useState, useEffect } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import axios from "axios";
import { toast } from "react-toastify";
import { ShieldCheck, ArrowLeft, Loader2 } from "lucide-react";

function TwoFactorLogin() {
  const navigate = useNavigate();
  const location = useLocation();
  const [code, setCode] = useState("");
  const [loading, setLoading] = useState(false);
  const [tempToken, setTempToken] = useState("");

  useEffect(() => {
    const token = location.state?.tempToken;
    if (!token) {
      toast.error("Invalid session. Please login again.", { theme: "dark" });
      navigate("/login");
    } else {
      setTempToken(token);
    }
  }, [location, navigate]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (code.length !== 6) {
      toast.warning("Please enter a 6-digit verification code");
      return;
    }

    setLoading(true);
    try {
      const response = await axios.post(
        "http://localhost:5000/api/v1/auth/verify-2fa-login",
        { code, tempToken },
        { withCredentials: true }
      );

      if (response.data.success) {
        toast.success("Authentication successful!");
        localStorage.setItem("user", JSON.stringify(response.data));
        navigate("/");
      }
    } catch (error) {
      toast.error(error.response?.data?.message || "Invalid authenticator code");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex items-center justify-center min-h-[85vh] bg-slate-50 dark:bg-slate-950 p-4 transition-colors">
      <div className="w-full max-w-md p-8 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl shadow-xl space-y-6 animate-scale-up">
        
        {/* Header Icon */}
        <div className="flex flex-col items-center text-center space-y-2">
          <div className="p-3 bg-indigo-50 dark:bg-indigo-950/20 text-indigo-500 rounded-2xl">
            <ShieldCheck className="w-8 h-8" />
          </div>
          <h1 className="text-xl sm:text-2xl font-bold text-slate-800 dark:text-slate-100">
            Two-Step Verification
          </h1>
          <p className="text-xs sm:text-sm text-slate-500 dark:text-slate-400">
            Enter the 6-digit security code generated by your authenticator application.
          </p>
        </div>

        {/* Input Form */}
        <form onSubmit={handleSubmit} className="space-y-6">
          <div className="space-y-2">
            <label className="block text-xs font-semibold text-slate-600 dark:text-slate-400 uppercase tracking-wider text-center">
              Security Code
            </label>
            <input
              type="text"
              maxLength="6"
              placeholder="000000"
              value={code}
              onChange={(e) => setCode(e.target.value.replace(/\D/g, ""))}
              className="w-full text-center tracking-widest font-mono text-2xl font-bold py-3 border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-950 rounded-2xl focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 text-slate-800 dark:text-slate-100"
              autoFocus
            />
          </div>

          <button
            type="submit"
            disabled={loading || code.length !== 6}
            className="w-full py-3 bg-indigo-600 hover:bg-indigo-500 text-white rounded-2xl font-bold text-sm sm:text-base transition duration-200 flex items-center justify-center gap-2 shadow-sm disabled:opacity-55"
          >
            {loading ? (
              <>
                <Loader2 className="w-5 h-5 animate-spin" />
                Verifying...
              </>
            ) : (
              "Confirm Code"
            )}
          </button>
        </form>

        {/* Back Button */}
        <div className="text-center pt-2">
          <button
            onClick={() => navigate("/login")}
            className="inline-flex items-center gap-1.5 text-xs font-semibold text-slate-500 dark:text-slate-400 hover:text-indigo-500 transition"
          >
            <ArrowLeft className="w-3.5 h-3.5" />
            Back to login page
          </button>
        </div>

      </div>
    </div>
  );
}

export default TwoFactorLogin;
